#!/usr/bin/env bash
# e2e-pipeline-test.sh — Synthetic end-to-end pipeline health check
# Creates a real test submission, polls until station:done, alerts #ops on failure.
#
# Usage: bash scripts/e2e-pipeline-test.sh
# Env (inherited from harness .env or parent):
#   SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, GITHUB_TOKEN, GITHUB_REPO
#   FACTORY_APP_URL, FACTORY_SECRET
#   DISCORD_WEBHOOK_URL  (optional — for #ops alerts)
#   E2E_TEST_USER_ID     (Supabase user ID to own the test submission)
#   E2E_MAX_WAIT_MIN     (default 90 — minutes before timeout FAIL)
#   E2E_LABEL_TIMEOUT_MIN (default 30 — minutes before stall WARN per station)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/../.env" 2>/dev/null || true

REPO="${GITHUB_REPO:-ascendantventures/harness-beta-test}"
SUPABASE_URL="${SUPABASE_URL:-}"
SUPABASE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-}"
DISCORD_WEBHOOK="${DISCORD_WEBHOOK_URL:-}"
TEST_USER_ID="${E2E_TEST_USER_ID:-ffe1edfa-e603-4250-b19f-7cefa6a2d395}"

MAX_WAIT_MIN="${E2E_MAX_WAIT_MIN:-90}"
POLL_INTERVAL=60
LABEL_TIMEOUT_MIN="${E2E_LABEL_TIMEOUT_MIN:-30}"

# ── Helpers ──────────────────────────────────────────────────────────────
log() { echo "[$(date -u +%H:%M:%S)] $*"; }

notify() {
  local level="$1"
  local msg="$2"
  local color
  case "$level" in
    PASS)  color=3066993  ;;
    FAIL)  color=15158332 ;;
    WARN)  color=16776960 ;;
    *)     color=10070709 ;;
  esac
  log "[$level] $msg"
  if [ -n "$DISCORD_WEBHOOK" ]; then
    local safe_msg
    safe_msg=$(echo "$msg" | python3 -c "import json,sys; print(json.dumps(sys.stdin.read()))" 2>/dev/null | tr -d '"')
    curl -s -X POST "$DISCORD_WEBHOOK" \
      -H "Content-Type: application/json" \
      -d "{\"embeds\":[{\"title\":\"E2E Pipeline: $level\",\"description\":\"$safe_msg\",\"color\":$color}]}" \
      >/dev/null 2>&1 || true
  fi
}

cleanup() {
  local issue_num="${1:-}"
  [ -z "$issue_num" ] && return
  log "Cleaning up test issue #$issue_num..."
  gh issue close "$issue_num" --repo "$REPO" \
    --comment "E2E test complete — closing synthetic issue" 2>/dev/null || true
  for label in station:intake station:spec station:design station:build station:provisioned station:qa station:uat station:done station:stuck station:bugfix; do
    gh issue edit "$issue_num" --repo "$REPO" --remove-label "$label" 2>/dev/null || true
  done
  if [ -n "${SUBMISSION_ID:-}" ] && [ -n "$SUPABASE_URL" ] && [ -n "$SUPABASE_KEY" ]; then
    curl -s -X DELETE \
      "$SUPABASE_URL/rest/v1/submissions?id=eq.$SUBMISSION_ID" \
      -H "apikey: $SUPABASE_KEY" \
      -H "Authorization: Bearer $SUPABASE_KEY" >/dev/null 2>&1 || true
  fi
}

# ── Step 1: Create synthetic test issue ──────────────────────────────────
TIMESTAMP=$(date -u +%Y%m%dT%H%M)
ISSUE_TITLE="[E2E Test] Synthetic pipeline smoke test — $TIMESTAMP"

log "Creating synthetic test issue..."
ISSUE_URL=$(gh issue create \
  --repo "$REPO" \
  --title "$ISSUE_TITLE" \
  --body "**E2E Pipeline Smoke Test — $TIMESTAMP**

This is an automatically created synthetic issue to validate the full factory pipeline.

\`\`\`json
{
  \"business\": \"A minimal todo list app for automated E2E pipeline validation. Tracks tasks with due dates and priority levels for a small team.\",
  \"problem\": \"Validate the full factory pipeline completes end-to-end from intake to delivery within the SLA window.\",
  \"tech_stack\": [\"Next.js\", \"Supabase\"],
  \"project_type\": \"web-app\",
  \"auth_required\": true,
  \"payment_required\": false
}
\`\`\`

_Auto-generated by scripts/e2e-pipeline-test.sh — safe to close._" \
  --label "station:intake" --label "complexity:simple" 2>&1)

ISSUE_NUM=$(echo "$ISSUE_URL" | grep -oP '\d+$')
if [ -z "$ISSUE_NUM" ]; then
  notify FAIL "Could not create test issue. Output: $ISSUE_URL"
  exit 1
fi
log "Created test issue #$ISSUE_NUM"

# Create Supabase submission record
SUBMISSION_ID=""
if [ -n "$SUPABASE_URL" ] && [ -n "$SUPABASE_KEY" ]; then
  GITHUB_ISSUE_URL="https://github.com/$REPO/issues/$ISSUE_NUM"
  SUB_RESULT=$(curl -s -X POST \
    "$SUPABASE_URL/rest/v1/submissions" \
    -H "apikey: $SUPABASE_KEY" \
    -H "Authorization: Bearer $SUPABASE_KEY" \
    -H "Content-Type: application/json" \
    -H "Prefer: return=representation" \
    -d "{
      \"github_issue_url\": \"$GITHUB_ISSUE_URL\",
      \"created_by\": \"$TEST_USER_ID\",
      \"station\": \"intake\",
      \"status\": \"active\"
    }" 2>/dev/null)
  SUBMISSION_ID=$(echo "$SUB_RESULT" | python3 -c \
    "import json,sys; rows=json.load(sys.stdin); print(rows[0]['id'] if rows else '')" 2>/dev/null || echo "")
  [ -n "$SUBMISSION_ID" ] && log "Submission ID: $SUBMISSION_ID" || log "Warning: Supabase submission not created"
fi

trap "cleanup $ISSUE_NUM" EXIT

# ── Step 2: Poll for station:done ─────────────────────────────────────────
START_TS=$(date +%s)
MAX_WAIT_SEC=$((MAX_WAIT_MIN * 60))
LABEL_TIMEOUT_SEC=$((LABEL_TIMEOUT_MIN * 60))

LAST_LABEL="station:intake"
LABEL_SINCE=$(date +%s)
STATION_HISTORY=()

log "Polling for station:done (max ${MAX_WAIT_MIN}m, stall alert at ${LABEL_TIMEOUT_MIN}m per station)..."

while true; do
  ELAPSED=$(( $(date +%s) - START_TS ))

  if [ $ELAPSED -gt $MAX_WAIT_SEC ]; then
    CURRENT_LABELS=$(gh issue view "$ISSUE_NUM" --repo "$REPO" \
      --json labels --jq '[.labels[].name | select(startswith("station:"))] | join(", ")' 2>/dev/null || echo "unknown")
    HISTORY_STR=$(printf '%s ' "${STATION_HISTORY[@]:-}")
    notify FAIL "Timeout after ${MAX_WAIT_MIN}m — stuck at: $CURRENT_LABELS | History: $HISTORY_STR | https://github.com/$REPO/issues/$ISSUE_NUM"
    exit 1
  fi

  CURRENT_LABEL=$(gh issue view "$ISSUE_NUM" --repo "$REPO" \
    --json labels --jq '[.labels[].name | select(startswith("station:"))] | first // "none"' 2>/dev/null || echo "error")

  if [ "$CURRENT_LABEL" != "$LAST_LABEL" ]; then
    ELAPSED_AT=$(( $(date +%s) - START_TS ))
    log "Advance: $LAST_LABEL → $CURRENT_LABEL (${ELAPSED_AT}s)"
    STATION_HISTORY+=("$LAST_LABEL→$CURRENT_LABEL@${ELAPSED_AT}s")
    LAST_LABEL="$CURRENT_LABEL"
    LABEL_SINCE=$(date +%s)
  fi

  # Success
  if [ "$CURRENT_LABEL" = "station:done" ] || [ "$CURRENT_LABEL" = "none" ]; then
    TOTAL_SEC=$(( $(date +%s) - START_TS ))
    TOTAL_MIN=$((TOTAL_SEC / 60))
    HISTORY_STR=$(printf '%s ' "${STATION_HISTORY[@]:-}")
    notify PASS "Completed in ${TOTAL_MIN}m ${TOTAL_SEC}s | Path: $HISTORY_STR | https://github.com/$REPO/issues/$ISSUE_NUM"
    exit 0
  fi

  # Stuck
  if [ "$CURRENT_LABEL" = "station:stuck" ]; then
    TOTAL_SEC=$(( $(date +%s) - START_TS ))
    HISTORY_STR=$(printf '%s ' "${STATION_HISTORY[@]:-}")
    notify FAIL "Reached station:stuck after ${TOTAL_SEC}s | History: $HISTORY_STR | https://github.com/$REPO/issues/$ISSUE_NUM"
    exit 1
  fi

  # Stall warning
  LABEL_AGE=$(( $(date +%s) - LABEL_SINCE ))
  if [ $LABEL_AGE -gt $LABEL_TIMEOUT_SEC ]; then
    HISTORY_STR=$(printf '%s ' "${STATION_HISTORY[@]:-}")
    notify WARN "Stall: $CURRENT_LABEL for ${LABEL_AGE}s | History: $HISTORY_STR"
    LABEL_SINCE=$(date +%s)  # reset to avoid spam
  fi

  sleep "$POLL_INTERVAL"
done
